spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/probe
    password: root
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
